name: Home Assistant MCP Server
version: "2.0.0"
slug: ha-mcp-server
description: Model Context Protocol server for Claude.ai integration with Home Assistant
url: https://github.com/shaike1/ha-mcp
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
map:
  - config:rw
  - ssl:ro
  - share:rw
  - media:ro
options:
  port: 3000
  server_url: ""
  admin_username: "admin"
  admin_password: ""
  log_level: "info"
  multi_tenant: false
  enable_user_registration: false
schema:
  port: port
  server_url: url
  admin_username: str
  admin_password: password
  log_level: list(debug|info|warn|error)
  multi_tenant: bool
  enable_user_registration: bool
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: MCP Server API
image: "shaikeme/ha-mcp-server"
host_network: false
homeassistant_api: true
hassio_api: true
hassio_role: default
auth_api: false
ingress: true
ingress_port: 3000
panel_icon: mdi:robot
panel_title: MCP Server
panel_admin: true