name: Test Docker Hub Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Docker Hub Login
      run: |
        echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Token exists: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        echo "Token length: ${#DOCKERHUB_TOKEN}"
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Hub Login Test
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}